#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "triangle/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_restricted_triangle, m) {
  m.doc() = "libigl triangle module python bindings";
  // generated by cmake
#include "triangle/BINDING_INVOCATIONS.in"
}

