#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "copyleft/tetgen/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_copyleft_tetgen, m) {
  m.doc() = "libigl tetgen module python bindings";
  // generated by cmake
#include "copyleft/tetgen/BINDING_INVOCATIONS.in"
}

