#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "spectra/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_spectra, m) {
  m.doc() = "libigl spectra module python bindings";
  // generated by cmake
#include "spectra/BINDING_INVOCATIONS.in"
}
