#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "copyleft/cgal/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_copyleft_cgal, m) {
  m.doc() = "libigl cgal module python bindings";
  // generated by cmake
#include "copyleft/cgal/BINDING_INVOCATIONS.in"
}

