#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "cycodebase/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_cycodebase, m) {
  m.doc() = "libigl cycodebase module python bindings";
  // generated by cmake
#include "cycodebase/BINDING_INVOCATIONS.in"
}
