#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_core, m) {
  m.doc() = "libigl python bindings";
  // generated by cmake
#include "BINDING_INVOCATIONS.in"
}

