#include <nanobind/nanobind.h>
namespace nb = nanobind;

// generated by cmake
#include "embree/BINDING_DECLARATIONS.in"

NB_MODULE(pyigl_embree, m) {
  m.doc() = "libigl embree module python bindings";
  // generated by cmake
#include "embree/BINDING_INVOCATIONS.in"
}

